name: Local Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python:
          - 3.6
          - 3.7
          - 3.8
          - 3.x
        architecture:
          - x64
          - x86
        # x86 builds are only meaningful for Windows
        exclude:
          - os: ubuntu-latest
            architecture: x86
          - os: macos-latest
            architecture: x86
    steps:
      - uses: actions/checkout@2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.architecture }}
      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade tox
      - name: run test
        run: |
          tox -e build
          python test/test_pipx-in-pipx.py --dist-directory "$(pwd)/dist"
