name: Local Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: true
      matrix:
        platform:
          - os: ubuntu-latest
            architecture: x64
          - os: macos-latest
            architecture: x64
          - os: windows-latest
            architecture: x86
          - os: windows-latest
            architecture: x64
        python:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - 3.x
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.platform.architecture }}
      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade tox
      - name: run test
        run: |
          tox -e build
          python test/test_pipx-in-pipx.py --dist-directory "$(pwd)/dist"
